### ISSUE TITLE
Error on Emitter stardust upgrade to v.4.0.0

### ISSUE THREAD

**Issue by nicoglori** [qlik-oss/nebula.js#1262]
## 🐛 Bug report

Hi,
while upgrading @nebula.js/stardust to v.4.0.0 I have this error on building my library:
**ERROR in ../node_modules/@nebula.js/stardust/types/index.d.ts:175:31 - error TS2304: Cannot find name 'Emitter'.
175 export function useEmitter(): Emitter;**

1. upgrade stardust to 4.0.0
2. build the project

### Versions

- nebula.js: 4.0.0
- Platform: angular 8
- Browser: chrome

**Comment by flash-222** [comment]
Hi,
faced exactly the same problem:
**Error: node_modules/@nebula.js/stardust/types/index.d.ts:185:31 - error TS2304: Cannot find name 'Emitter'.**
**Cannot find name 'Emitter'.ts(2304)
type Emitter = /*unresolved*/ any**

As a temporary solution, I just commented out the following line of code:
`export function useEmitter(): Emitter;`

The documentation says that useEmitter() is an experimental, so I hope that disabling it will not affect the application.

**Versions**
- nebula.js: 4.2.0
- Platform: angular 16.0.3
- Browser: chrome

**Comment by Caele** [comment]
The only missing part is the typescript Emitter type, which is due to Nebula itself not being in typescript yet but only generating types off jsdocs. When adding the useEmitter hook we added the Emitter type to the spec configuration: https://github.com/qlik-oss/nebula.js/blob/master/apis/stardust/api-spec/spec.conf.js#L44 but that isn't properly transferred into a type.
You should be able to ignore the error depending on what you TS setup is, but i will also look at adding the type properly.
