### ISSUE TITLE
sn-bar-chart & sn-line-chart throwing deprecation warnings

### ISSUE THREAD

**Issue by frankAOD** [qlik-oss/nebula.js#1315]
## 🐛 Bug report

sn-bar-chart and sn-line-chart throw constant warnings to the developer console after update to latest versions.
Charts still function.

Warning is:

useContraints has been deprecated, please change to useInteractions instead. Note that interactions uses inverted values compared to contraints.

### Versions

    "@nebula.js/sn-bar-chart": "^1.33.0",
    "@nebula.js/sn-line-chart": "^1.29.0",
    "@nebula.js/stardust": "^4.2.3",
    "enigma.js": "^2.11.0",

**Comment by M1CK431** [comment]
In addition I can't found the source code for both that charts types so I can't even try to fix it myself...

**Comment by M1CK431** [comment]
In the meantime, as a workaround, we could still patch the minified js files direclty instead:
```sh
sed -i 's/e\.useConstraints\(\)/(a,b)=>e.useInteractions(b,a)/' \
  node_modules/@nebula.js/sn-bar-chart/dist/sn-bar-chart.js \
  node_modules/@nebula.js/sn-line-chart/dist/sn-line-chart.js
```

**Comment by M1CK431** [comment]
Same issue with `sn-pie-chart`

**Comment by Caele** [comment]
It is a warning, not an error, they will be updated given time.

**Comment by M1CK431** [comment]
Excuse me @Caele , just to be sure, you close an issue without fixing it juste because "it is a warning"? 😮 
Have you notice that this warning could be fired in loop, and so the browser ends by crashing after something like 3000+ warnings (reached in a few minutes)?
In addition, could you please explain why an MIT licensed file is not published here?

**Comment by frankAOD** [comment]
> It is a warning, not an error, they will be updated given time.

Hi @Caele, understood that it's a warning, however if there are several or many charts on a dashboard this warning is spamming the browser constantly and quickly causes it to fall over (also mentioned by @M1CK431, above). Each instance of a Nebula chart throws the warning constantly every time the model changes. 

It's completely unusable at any scale with this warning happening.

**Comment by frankAOD** [comment]
@Caele - is there any update on this issue? The deprecation warnings continue to negatively effect performance and make development very difficult due to the massive stream of warnings in the console.

**Comment by Caele** [comment]
Sorry for the very late reply, I did not notice the activity after closing this.

I closed this issue because the warning is a dev warning, not a production one, so in my mind it wouldn't be very intrusive. But I can understand the issue, so I will add a restriction to only fire it once per component per session (https://github.com/qlik-oss/nebula.js/pull/1484)

As for the MIT license on some of the charts, its is my understanding that MIT doesn't require the source code to be public, its just means you can do whatever you want with the package. But I'll investigate this a bit.
