### ISSUE TITLE
npm run sense - bundler ignores backslash in directory

### ISSUE THREAD

**Issue by rkassoss** [qlik-oss/nebula.js#489]
## 🐛 Bug report
When I try to package an extension using `npm run sense` I get an error about the node modules not being resolved correctly. Seems like the bundler removes the "/" from the directory before running an additional script. See attached:
<img width="713" alt="Capture" src="https://user-images.githubusercontent.com/11234344/90078448-f206db80-dcd2-11ea-97d5-4d70e46d56b6.PNG">

### Steps to Reproduce

Follow the exact steps of the ["Build a Hello world extension using NebulaJS".](https://qlik.dev/tutorials/build-a-helloworld-extension-using-nebulajs)

### Versions

- nebula.js: latest
- Platform: ?
- Browser: ?

**Comment by rjriel** [comment]
Javascript usually treats single backslashes to escape characters. Try putting double backslashes in your string and see if that solves the problem. I imagine the `Unterminated string constant` error message is because you are ending your string with a single `\` so you're actually escaping the closing single quote, meaning your string doesn't close.
